2023-05-28 14:29:18,767 (7ff8fb383808) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 248a2da (Thu May 18 13:03:39 UTC 2023)
2023-05-28 14:29:18,768 (7ff8fb383808) :  DEBUG (core:361) - Using the elevated policy
2023-05-28 14:29:18,768 (7ff8fb383808) :  DEBUG (core:450) - Starting runtime component.
2023-05-28 14:29:18,769 (7ff8fb383808) :  DEBUG (core:450) - Starting caching component.
2023-05-28 14:29:18,769 (7ff8fb383808) :  DEBUG (core:450) - Starting data component.
2023-05-28 14:29:18,769 (7ff8fb383808) :  DEBUG (core:450) - Starting networking component.
2023-05-28 14:29:18,769 (7ff8fb383808) :  DEBUG (networking:266) - No cookie jar found
2023-05-28 14:29:18,770 (7ff8fb383808) :  DEBUG (networking:434) - Setting the default network timeout to 20.0
2023-05-28 14:29:18,770 (7ff8fb383808) :  DEBUG (core:450) - Starting localization component.
2023-05-28 14:29:18,770 (7ff8fb383808) :  INFO (localization:409) - Setting the default locale to en-us
2023-05-28 14:29:18,771 (7ff8fb383808) :  DEBUG (core:450) - Starting messaging component.
2023-05-28 14:29:18,771 (7ff8fb383808) :  DEBUG (core:450) - Starting debugging component.
2023-05-28 14:29:18,771 (7ff8fb383808) :  DEBUG (core:450) - Starting services component.
2023-05-28 14:29:18,771 (7ff8f803eb38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2023-05-28 14:29:18,771 (7ff8fb383808) :  DEBUG (core:450) - Starting myplex component.
2023-05-28 14:29:18,772 (7ff8fb383808) :  DEBUG (core:450) - Starting notifications component.
2023-05-28 14:29:18,881 (7ff8fb383808) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2023-05-28 14:29:18,885 (7ff8fb383808) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-05-28 14:29:18,889 (7ff8fb383808) :  ERROR (networking:197) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-05-28 14:29:18,891 (7ff8fb383808) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 221, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 159, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2023-05-28 14:29:18,897 (7ff8f7e75b38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2023-05-28 14:29:18,897 (7ff8fb383808) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2023-05-28 14:29:18,898 (7ff8f7e75b38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2023-05-28 14:29:18,899 (7ff8fb383808) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2023-05-28 14:29:18,899 (7ff8f7e2fb38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400'
2023-05-28 14:29:18,900 (7ff8fb383808) :  DEBUG (core:150) - Finished starting framework core
2023-05-28 14:29:18,900 (7ff8fb383808) :  DEBUG (core:560) - Loading plug-in code
2023-05-28 14:29:18,941 (7ff8f7e75b38) :  DEBUG (services:362) - Loaded services
2023-05-28 14:29:18,945 (7ff8f7e2fb38) :  DEBUG (core:538) - Machine identifier is f9bc795cf65c88a148b297975c19a35fac926692
2023-05-28 14:29:18,946 (7ff8f7e2fb38) :  DEBUG (core:539) - Server version is 1.32.2.7100-248a2daf0
2023-05-28 14:29:19,010 (7ff8f7e52b38) :  DEBUG (services:438) - No shared code to load
2023-05-28 14:29:19,261 (7ff8fb383808) :  DEBUG (core:566) - Finished loading plug-in code
2023-05-28 14:29:19,262 (7ff8fb383808) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2023-05-28 14:29:19,263 (7ff8fb383808) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2023-05-28 14:29:19,263 (7ff8fb383808) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2023-05-28 14:29:38,255 (7ff8fb383808) :  INFO (core:611) - Started plug-in
2023-05-28 14:29:38,255 (7ff8fb383808) :  DEBUG (socketinterface:160) - Starting socket server
2023-05-28 14:29:38,256 (7ff8fb383808) :  DEBUG (runtime:1117) - Created a thread named 'start'
2023-05-28 14:29:38,256 (7ff8fb383808) :  INFO (socketinterface:184) - Socket server started on port 43693
2023-05-28 14:29:38,256 (7ff8fb383808) :  INFO (pipeinterface:25) - Entering run loop
2023-05-28 14:29:38,256 (7ff8fb383808) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2023-05-28 14:29:38,257 (7ff8fb383808) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2023-05-28 14:29:38,258 (7ff8fb383808) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2023-05-28 14:29:38,265 (7ff8f731ab38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-05-28 14:29:38,272 (7ff8f72f3b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-05-28 14:29:38,277 (7ff8f731ab38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-05-28 14:29:38,277 (7ff8f731ab38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-05-28 14:29:38,277 (7ff8f72f3b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-05-28 14:29:38,278 (7ff8f731ab38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-05-28 14:29:38,278 (7ff8f72f3b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-05-28 14:29:38,278 (7ff8f731ab38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2023-05-28 14:29:38,279 (7ff8f72f3b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-05-28 14:29:38,279 (7ff8f72f3b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
